### PR TITLE
Upgrade dependency versions of nalegbra, cgmath, and num

### PR DESCRIPTION
**Pull request by IsaacTru**
Upgrade deps to latest version and therefore bump major version since it is not backwards compatible

### CODE REVIEW

**Comment by IsaacTru** [comment]
Oops! I submitted too soon. The following test is failing:

```
---- primitives::test::test_circle_distance stdout ----
thread 'primitives::test::test_circle_distance' panicked at 'assertion failed: c.contains(&p1)', src/primitives.rs:581:9
```

**Comment by IsaacTru** [comment]
Okay. All better :)

**Comment by Palladinium** [comment]
Thank you! Quick note: `nalgebra` has been updated again to `0.28`

**Comment by Stoeoef** [comment]
Hello! Sorry for not getting back to your pull request in time. To be honest, I wasn't sure if I would continue actively developing spade, hence the delay.
That being said, I'm happy to report being "back in" and plan to release a revamped spade 2.0 release next weekend!
Unfortunately, I decided against keeping the `nalgebra` support due to the maintenance burden it causes. Thus, this PR can't be applied any more.

That being said, I do think that a nice integration with some external geometry library would be a nice feature. I'll open an issue for just that to track that and put it on the 3.0 wish list.
I think the most promising result these days might be to depend completely on `nalgebra` instead of having something like a `PointN` trait - this would allow `spade` to use all nice vector functions internally.

Sorry again for not getting back here in time and not being able to merge this right now. If you want to participate in the discussion about how to add support for `nalgebra`, please feel free to join the appropriate issue.

**Pull request closed without merging**
